### ISSUE TITLE
IconServlet exception on wrong file format

### ISSUE THREAD

**Issue by ThomDietrich** [kaikreuzer/openhab-core#54]
Following up on https://community.openhab.org/t/exception-handling-and-logging/12509

A NullPointerException exception is raised when (1) svg is configured as icon file format, (2) file exists as png and (3) filename consists of "state".

Reproduce:
* no file but sitemap contains `icon="sunset"` -> no icon in BasicUI (also no warning) 
* file `sunset.png` and sitemap contains `icon="sunset"` -> no icon in BasicUI, no exception
* file `sunset-test.png` and sitemap contains `icon="sunset-test"` -> no icon in BasicUI and NullPointerException raised

**Comment by kaikreuzer** [comment]
Sorry, I cannot reproduce and the exception that you have provided int the forum seems to be from a rather old build, since the according sources [do not exist anymore](https://github.com/kaikreuzer/openhab-core/commit/ae2d55f9d417b9292095c26aba56c45ab993d7e9) since a month.

So sorry to have you reverted again, but if you can still reproduce your issue on the latest snapshot, please provide the full exception and enter an issue at https://github.com/eclipse/smarthome/issues.
